---
title: "Update Auchencorth Meteorological Data"
author: "Peter Levy"
date: "`r Sys.Date()`"
output:
  html_document:
    self_contained: yes
    fig_caption: yes
---

```{r startup, eval=TRUE, echo=FALSE}
library(pins)
library(dplyr)
library(ggplot2)
library(data.table)
board <- pins::board_connect()
```

```{r update, eval=TRUE, echo=FALSE}
# Read in ERA5 data----
# url_era5 <- paste0("https://gws-access.jasmin.ac.uk/public/dare_uk/plevy/UK-AMo/df_era5.rds")
# url_era5 <- paste0("https://gws-access.jasmin.ac.uk/public/ukem/UK-AMo/df_era5.rds")
url_era5 <- paste0("https://gws-access.jasmin.ac.uk/public/eddystore/UK-AMO/dt_era5.rds")

system.time(df_era5 <- readRDS(url(url_era5, "rb")))

paste("ERA5 data from", min(df_era5$DATECT), "to",  max(df_era5$DATECT))

# Reading in the logger data----
this_year <- as.POSIXlt(Sys.Date())$year + 1900
# url_mainmet <- paste0("https://gws-access.jasmin.ac.uk/public/dare_uk/plevy/UK-AMo/UK-AMo_mainmet_", this_year, "_agf.rds")
# url_mainmet <- paste0("https://gws-access.jasmin.ac.uk/public/ukem/UK-AMo/UK-AMo_mainmet_", this_year, "_agf.rds")
url_mainmet <- paste0("https://gws-access.jasmin.ac.uk/public/eddystore/UK-AMO/lev1/UK-AMO_BM.rds")

system.time(l_lev1 <- readRDS(url(url_mainmet, "rb")))

# temporariliy stick with old name "df" even though it is now a data table
l_lev1$df    <- l_lev1$dt
l_lev1$df_qc <- l_lev1$dt_qc
paste("Level 1 data from", min(l_lev1$df$DATECT), "to",  max(l_lev1$df$DATECT))

# subset level 1 data to end of era5 data
l_lev1$df    <- l_lev1$df[DATECT <= max(df_era5$DATECT)]
l_lev1$df_qc <- l_lev1$df_qc[DATECT <= max(df_era5$DATECT)]

pins::pin_write(board,
  df_era5,
  name = "plevy/era5_data", type = "rds")
  
pins::pin_write(board,
  l_lev1,
  name = "plevy/level1_data", type = "rds")
```

```{r dataSummary, eval=TRUE, echo=TRUE}
dfs <- subset(df_era5, DATECT >= "2022-01-01")
paste("ERA5 data from", min(dfs$DATECT), "to",  max(dfs$DATECT))
with(dfs, plot(DATECT, TS))
summary(dfs)
```