library(shiny)
library(shinydashboard)
library(shinyjs)
library(shinythemes)
library(lubridate)
library(plyr)
library(dplyr)
library(ggplot2)
library(ggiraph)
library(ROracle) 
library(readxl)
library(DT)
library(data.table)
library(mgcv)
library(shinyalert)

shinyApp(ui = ui, server = server, onStart = )